/* over.flp — auto-generated by tools/flp2c.py
   Tempo: 140.0 BPM  PPQ: 96  SR: 22050 */
#include "../core/audio.h"

/* ch0 "NES VST 1.2" wave=0 (7 notes) */
static const Note _over_c0[] = {
    {277.183f,37800},
    {415.305f,18900},
    {220.000f,18900},
    {207.652f,37800},
    {369.994f,18900},
    {184.997f,18900},
    {311.127f,18900},
};

const SongDef song_over = {
    1,
    {
        { _over_c0, 7, 0 },
    }
};
