#!/usr/bin/env python3
"""FLP -> C converter for TinyHero audio.c.

Usage:
    python3 tools/flp2c.py                  # convert all assets/music/*.flp
    python3 tools/flp2c.py path/to/song.flp # convert one file

Outputs one .c file per FLP into src/music/, each containing Note arrays and
a SongDef struct that audio.c can play with audioPlaySong().
"""

import sys, os, re, glob, math
import pyflp
from pyflp.arrangement import PatternPLItem

SR = 22050

_NOTE_NAMES = ("C","C#","D","D#","E","F","F#","G","G#","A","A#","B")

def _key_to_raw(key_str):
    """Parse PyFLP key string (e.g. 'C4', 'F#5') to raw note index 0-131.
    PyFLP convention: C0=0, A5=69 (=440 Hz)."""
    if len(key_str) >= 3 and key_str[1] == '#':
        note, octave = key_str[:2], int(key_str[2:])
    else:
        note, octave = key_str[0], int(key_str[1:])
    return _NOTE_NAMES.index(note) + octave * 12

def _raw_to_freq(raw):
    """Raw note index to Hz. A5(69)=440 Hz."""
    return 440.0 * (2.0 ** ((raw - 69.0) / 12.0))

def _c_name(s):
    s = s.lower()
    s = re.sub(r'[^a-z0-9]+', '_', s)
    return s.strip('_')

def _guess_wave(ch_name, notes):
    """Heuristic: map channel name / note stats to wave type.
    0=triangle  1=square  3=noise  4=sine  5=Karplus-Strong"""
    n = (ch_name or '').lower()
    if 'noise' in n:                   return 3
    if 'triangle' in n:                return 0
    if 'square' in n or 'pulse' in n:  return 1
    if 'piano' in n or 'keys' in n:    return 4
    if 'bass' in n:                    return 0
    if not notes:                      return 1

    raws    = [_key_to_raw(note.key) for note in notes]
    avg_len = sum(note.length for note in notes) / len(notes)
    p_range = (max(raws) - min(raws)) if len(raws) > 1 else 0

    # Short notes with narrow pitch range → percussive → noise
    if avg_len < 60 and p_range <= 5:  return 3
    # Very long notes → sustained pad → triangle
    if avg_len > 200:                  return 0
    # Default: square wave (NES pulse / melodic)
    return 1

def _build_timeline(all_clips, rack_ch, ppq, bpm):
    """Return list of (freq_hz, dur_samples) for one rack channel.
    Gaps become rests (freq=0). Simultaneous notes (chords) → highest pitch."""
    spb = SR / (bpm / 60.0 * ppq)   # samples per tick

    events = []  # (abs_tick, raw_note, length_ticks)
    for clip in all_clips:
        for note in clip.pattern.notes:
            if note.rack_channel != rack_ch:
                continue
            abs_pos = clip.position + note.position
            events.append((abs_pos, _key_to_raw(note.key), note.length))

    if not events:
        return []

    events.sort(key=lambda e: e[0])

    out = []
    prev_end = 0
    i = 0
    while i < len(events):
        pos, raw, length = events[i]

        # Gather all notes starting at same tick (chord) → take highest
        j = i + 1
        best_raw = raw
        best_len = length
        while j < len(events) and events[j][0] == pos:
            if events[j][1] > best_raw:
                best_raw = events[j][1]
                best_len = events[j][2]
            j += 1

        # Rest before this note
        if pos > prev_end:
            rest_dur = max(1, round((pos - prev_end) * spb))
            out.append((0.0, rest_dur))

        dur = max(1, round(best_len * spb))
        out.append((_raw_to_freq(best_raw), dur))
        prev_end = pos + best_len
        i = j

    return out

def convert(flp_path, out_path):
    print(f'  {os.path.basename(flp_path)}')
    p = pyflp.parse(flp_path)
    name = _c_name(os.path.splitext(os.path.basename(flp_path))[0])
    channels = list(p.channels)

    # Collect all pattern clips from the arrangement
    arr = list(p.arrangements)[0]
    all_clips = []
    for track in arr.tracks:
        for item in track:
            if isinstance(item, PatternPLItem):
                all_clips.append(item)

    # Discover rack channels used
    rack_channels = sorted({
        note.rack_channel
        for clip in all_clips
        for note in clip.pattern.notes
    })

    voices = []
    for rc in rack_channels:
        ch_name = getattr(channels[rc], 'name', None) if rc < len(channels) else None
        ch_notes = [
            note
            for clip in all_clips
            for note in clip.pattern.notes
            if note.rack_channel == rc
        ]
        timeline = _build_timeline(all_clips, rc, p.ppq, p.tempo)
        if not timeline:
            continue
        wave = _guess_wave(ch_name, ch_notes)
        voices.append((rc, ch_name or f'ch{rc}', wave, timeline))

    if not voices:
        print(f'    (no notes found, skipping)')
        return

    lines = [
        f'/* {os.path.basename(flp_path)} — auto-generated by tools/flp2c.py',
        f'   Tempo: {p.tempo} BPM  PPQ: {p.ppq}  SR: {SR} */',
        '#include "../core/audio.h"',
        '',
    ]

    arr_names = []
    for rc, ch_name, wave, timeline in voices:
        arr = f'_{name}_c{rc}'
        arr_names.append((arr, wave, len(timeline)))
        lines.append(f'/* ch{rc} "{ch_name}" wave={wave} ({len(timeline)} notes) */')
        lines.append(f'static const Note {arr}[] = {{')
        for freq, dur in timeline:
            if freq == 0.0:
                lines.append(f'    {{0.000f,{dur}}},')
            else:
                lines.append(f'    {{{freq:.3f}f,{dur}}},')
        lines.append('};')
        lines.append('')

    lines.append(f'const SongDef song_{name} = {{')
    lines.append(f'    {len(arr_names)},')
    lines.append('    {')
    for arr, wave, n in arr_names:
        lines.append(f'        {{ {arr}, {n}, {wave} }},')
    lines.append('    }')
    lines.append('};')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    total_notes = sum(len(v[3]) for v in voices)
    print(f'    -> {out_path}  ({len(voices)} voices, {total_notes} note entries)')

def main():
    music_dir = 'assets/music'
    out_dir   = 'src/music'
    os.makedirs(out_dir, exist_ok=True)

    if len(sys.argv) > 1:
        paths = sys.argv[1:]
    else:
        paths = sorted(glob.glob(os.path.join(music_dir, '*.flp')))

    if not paths:
        print('No FLP files found.')
        sys.exit(1)

    print(f'Converting {len(paths)} FLP file(s) -> {out_dir}/')
    for path in paths:
        name = _c_name(os.path.splitext(os.path.basename(path))[0])
        convert(path, os.path.join(out_dir, f'{name}.c'))

if __name__ == '__main__':
    main()
